package com.firebase.firebase_contact;

import android.content.Intent;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;

import java.util.HashMap;
import java.util.Map;

public class SignUpActivity extends AppCompatActivity {

    EditText signUpEmail, signUpPassword, signUpName, signUpPhone, SignUpConfPass;
    Button signUp_btn, cancel_btn;



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sign_up);

        getSupportActionBar().setDisplayShowHomeEnabled(true);
        getSupportActionBar().setLogo(R.mipmap.ic_launcher);
        getSupportActionBar().setDisplayUseLogoEnabled(true);
        getSupportActionBar().setBackgroundDrawable(new ColorDrawable(Color.BLACK));
        getSupportActionBar().setTitle("Expense App (Sign Up)");

        setContentView(R.layout.activity_sign_up);

        final Firebase ref = new Firebase("https://firstappkrunal.firebaseio.com/");



        signUpName = (EditText) findViewById(R.id.Name_editText);
        signUpPassword = (EditText) findViewById(R.id.SignPass_editText);
        signUpEmail = (EditText) findViewById(R.id.SignEmail_editText);
        signUpPhone = (EditText) findViewById(R.id.SignPhone_editText);
        SignUpConfPass = (EditText) findViewById(R.id.SignConfPass_editText);

        signUp_btn = (Button) findViewById(R.id.SignUp_button);
        cancel_btn = (Button) findViewById(R.id.Cancel_button);


        signUp_btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                final String fullName = signUpName.getText().toString();
                final String signPassword = signUpPassword.getText().toString();
                final String signEmail = signUpEmail.getText().toString();
                final String signConfPass = SignUpConfPass.getText().toString();
                final String signPhone = signUpPhone.getText().toString();

                if(fullName.isEmpty() || signPassword.isEmpty() || signEmail.isEmpty() || signPassword.isEmpty() || signPhone.isEmpty())
                {
                    Toast.makeText(SignUpActivity.this, "All fields are mandatory", Toast.LENGTH_SHORT).show();
                }
                else if(!signPassword.equals(signConfPass))
                {
                    Toast.makeText(SignUpActivity.this, "Password & Confirm Password doesn't match", Toast.LENGTH_SHORT).show();
                }
                else
                {
                    // Get a reference to our posts


                    // Attach an listener to read the data at our posts reference
                    ref.createUser(signEmail, signPassword, new Firebase.ValueResultHandler<Map<String, Object>>() {
                        @Override
                        public void onSuccess(Map<String, Object> result) {


                            Firebase postRef = ref.child("username");
                            Firebase newPostRef = postRef.push();

                            // Add some data to the new location
                            final Map<String, String> post1 = new HashMap<String, String>();
                            post1.put("email", signEmail);
                            post1.put("fullName", fullName);
                            post1.put("password", signPassword);
                            post1.put("phoneNumber", signPhone);
                            post1.put("picture", "default");
                            newPostRef.setValue(post1);

                            // Get the unique ID generated by push()
                            String postId = newPostRef.getKey();

                            System.out.println("Successfully created user account with uid: " + result.get("uid"));
                            Toast.makeText(SignUpActivity.this, "User Created Successfully", Toast.LENGTH_SHORT).show();
                            Intent i = new Intent(SignUpActivity.this, MainActivity.class);
                            startActivity(i);

                        }

                        @Override
                        public void onError(FirebaseError firebaseError) {
                            // there was an error
                            Toast.makeText(SignUpActivity.this, "Email Already Taken", Toast.LENGTH_SHORT).show();
                            finish();
                        }
                    });



                }


            }
        });


        cancel_btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                finish();

            }
        });
    }
}
